name: CI
on:
  pull_request:
  push:
    branches: [main]

permissions:
  actions: read
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install (skip scripts)
        run: npm ci --ignore-scripts --verbose
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t lint test build
      - name: Ensure PR has a changeset
        if: github.event_name == 'pull_request'
        run: npx changeset status --since=origin/main