name: CI
on:
  pull_request:
  push:
    branches: [main]

permissions:
  actions: read
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install (skip scripts)
        run: npm ci --ignore-scripts --verbose
      - uses: nrwl/nx-set-shas@v4
      - name: Compute affected tasks
        id: affected
        env:
          NX_DAEMON: "false"
        run: |
          set -e
          tasks=$(npx nx print-affected -t lint -t test -t build --select=tasks 2>/dev/null || true)
          if [ -z "$tasks" ]; then
            echo "run=false" >> $GITHUB_OUTPUT
          else
            echo "run=true" >> $GITHUB_OUTPUT
            echo "$tasks"
          fi
      - name: Affected (lint/test/build)
        if: steps.affected.outputs.run == 'true'
        env:
          NX_DAEMON: "false"
        run: npx nx affected -t lint test build --parallel=3 --output-style=stream --verbose
        timeout-minutes: 2
      - name: Nothing to run
        if: steps.affected.outputs.run == 'false'
        run: echo "No affected projects; skipping lint/test/build"
      - name: Ensure PR has a changeset
        if: github.event_name == 'pull_request'
        run: npx changeset status --since=origin/main