name: Release
on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Find merged PR for this commit
        id: pr
        uses: peter-evans/find-pull-request@v3
        with:
          commit: ${{ github.sha }}
      - name: Decide if we should skip publish
        id: gate
        run: |
          if [ -n "${{ steps.pr.outputs.pull-request-number }}" ]; then
            gh api repos/${{ github.repository }}/issues/${{ steps.pr.outputs.pull-request-number }}/labels \
              --jq '.[].name' > labels.txt
            if grep -qx 'no-release' labels.txt; then
              echo "skip=true" >> "$GITHUB_OUTPUT"
              exit 0
            fi
          fi
          echo "skip=false" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
        if: steps.gate.outputs.skip == 'false'
      - uses: nrwl/nx-set-shas@v4
        if: steps.gate.outputs.skip == 'false'
      - run: npx nx affected -t build --parallel=3 || npx nx run-many -t build --all
        if: steps.gate.outputs.skip == 'false'
      - name: Create Version PR or Publish
        if: steps.gate.outputs.skip == 'false'
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run version-packages
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Skipped due to no-release label
        if: steps.gate.outputs.skip == 'true'
        run: echo "Skip publishing: PR has the 'no-release' label."