name: Release
on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci

      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t build --parallel=3 || npx nx run-many -t build --all

      - name: Create Version PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run version-packages
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Echo published packages
        if: steps.changesets.outputs.published == 'true'
        run: echo '${{ steps.changesets.outputs.publishedPackages }}'